<a href="https://colab.research.google.com/github/NashirHussain07/DS-tasks/blob/main/100numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises


File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:

import numpy as np

print("NumPy Version:", np.__version__)
print("\nNumPy Configuration:")
print(np.show_config())

NumPy Version: 1.23.5

NumPy Configuration:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language 

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
[ [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ]

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:

import numpy as np

arr = np.zeros(10)  # Replace this with your array
memory_size = arr.nbytes

print(f"The memory size of the array is {memory_size} bytes.")

The memory size of the array is 80 bytes.


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: ignored

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
[ [0, 0, 0, 0, 1, 0, 0, 0, 0, 0] ]

[[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]]

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
[ [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49] ]

[[10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49]]

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
original_vector = [1, 2, 3, 4, 5]
reversed_vector = original_vector[::-1]

print(reversed_vector)

[5, 4, 3, 2, 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:

import numpy as np

matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:

import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)

print(nonzero_indices

SyntaxError: ignored

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:

[[1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:

import numpy as np

random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.84269168 0.43758201 0.63635281]
  [0.80101044 0.03083119 0.94232448]
  [0.66855047 0.86757918 0.61174756]]

 [[0.51229829 0.50367852 0.31731136]
  [0.11148627 0.58577665 0.07124518]
  [0.0406667  0.57714878 0.35027443]]

 [[0.07193649 0.62092217 0.25929278]
  [0.6670759  0.22023856 0.87801801]
  [0.31320794 0.12431882 0.66865643]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:

import numpy as np

# Create a 10x10 array with random values
random_array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:

import numpy as np

# Create a random vector of size 30
random_vector = np.random.rand(30)

# Find the mean value
mean_value = np.mean(random_vector)

print(f"Mean value: {mean_value}")

Mean value: 0.47016438557612134


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:

import numpy as np

# Create a 5x5 array (you can adjust the size as needed)
array_2d = np.ones((5, 5))

# Fill the inside with 0
array_2d[1:-1, 1:-1] = 0

print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:

import numpy as np

# Example existing array
existing_array = np.ones((3, 3))

# Add a border filled with 0's
new_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)

print(new_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:

nan
False
False
nan
True
False

NameError: ignored

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:

import numpy as np

# Create a 5x5 matrix
matrix = np.zeros((5, 5))

# Assign values 1, 2, 3, 4 below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:

import numpy as np

# Create an 8x8 matrix with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1  # Odd rows, even columns
checkerboard_matrix[::2, 1::2] = 1  # Even rows, odd columns

print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:

import numpy as np

shape = (6, 7, 8)
index_1d = 100

index_3d = np.unravel_index(index_1d, shape)

print(index_3d)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:

import numpy as np

# Create a single-row checkerboard pattern
row_pattern = np.array([0, 1] * 4)

# Use tile to create an 8x8 matrix
checkerboard_matrix = np.tile(row_pattern, (8,

SyntaxError: ignored

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:

import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)

print("Original matrix:")
print(random_matrix)
print("\nNormalized matrix:")
print(normalized_matrix)

Original matrix:
[[0.82039351 0.38146376 0.62148026 0.71388246 0.37611277]
 [0.44653961 0.59458593 0.58055972 0.07453843 0.38389178]
 [0.62692103 0.197689   0.78980852 0.35106254 0.4861447 ]
 [0.01861988 0.81993004 0.65706468 0.06301931 0.31835411]
 [0.71141764 0.90507202 0.75040449 0.08999684 0.58080066]]

Normalized matrix:
[[ 1.27002987 -0.43993376  0.49511219  0.8550887  -0.46077993]
 [-0.18641405  0.39033843  0.33569573 -1.63564027 -0.43047481]
 [ 0.51630811 -1.15587558  1.15087821 -0.55836952 -0.03212227]
 [-1.85348534  1.26822431  0.63374047 -1.68051596 -0.68579363]
 [ 0.84548636  1.59991678  0.99736967 -1.57541807  0.33663435]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:

import numpy as np

# Create a custom dtype for RGBA color
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Example usage with a single color
color = np.array((255, 128, 0, 255), dtype=color_dtype)

print(color)

(255, 128, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:

import numpy as np

# Create a 5x3 matrix
matrix_a = np.random.rand(5, 3)

# Create a 3x2 matrix
matrix_b = np.random.rand(3, 2)

# Perform matrix multiplication
result_matrix = np.dot(matrix_a, matrix_b)
# Alternatively, you can use the @ operator: result_matrix = matrix_a @ matrix_b

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nResultant Matrix:")
print(result_matrix)

Matrix A:
[[0.91896135 0.9013336  0.60166345]
 [0.14542636 0.50887993 0.53491495]
 [0.59435771 0.5162392  0.84243641]
 [0.73860722 0.67740186 0.26792954]
 [0.03492066 0.48678283 0.29710235]]

Matrix B:
[[0.47184249 0.21158514]
 [0.57987383 0.56046677]
 [0.8997708  0.54544988]]

Resultant Matrix:
[[1.49762397 1.02778335]
 [0.84500534 0.60774964]
 [1.3377965  0.87459901]
 [0.98238906 0.68208168]
 [0.5660737  0.44226874]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:

import numpy as np

# Create a 1D array
array_1d = np.array([1, 5, 3, 7, 2, 8, 4, 6, 9])

# Negate elements between 3 and 8 in place
array_1d[(array_1d > 3) & (array_1d < 8)] *= -1

print(array_1d)

[ 1 -5  3 -7  2  8 -4 -6  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:

9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z2 << Z >> 2Z <- Z1j*ZZ/1/1

SyntaxError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0): This will result in a runtime warning and the output will be nan (not a number) since it involves division by zero.np.array(0) // np.array(0): This will also result in a runtime warning and the output will be 0 since it involves floor division by zero.np.array([np.nan]).astype(int).astype(float): This expression converts a NumPy array containing nan to integers and then back to float. The result will be an array with a float containing nan.So, the results are:nan0nan

SyntaxError: ignored

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:

import numpy as np

# Example float array
float_array = np.array([-1.5, 2.3, -3.8, 4.5])

# Round away from zero
rounded_array = np.where(float_array > 0, np.ceil(float_array), np.floor(float_array))

print(rounded_array)

[-2.  3. -4.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
import numpy as np

# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)

print(common_values)
import numpy as np

# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)

print(common_values

SyntaxError: ignored

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:

import numpy as np

# Temporarily ignore all warnings
np.seterr(all='ignore')

# Your code here

# Reset warnings to their default behavior
np.seterr(all='warn')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
The expression is False.NumPy's np.sqrt(-1) will result in a complex number represented as 1j (the imaginary unit), while np.emath.sqrt(-1) will result in a complex number represented as 1j as well. Therefore, both sides of the equality are equal, and the expression is True.

SyntaxError: ignored

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:

from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-11-21
Today: 2023-11-22
Tomorrow: 2023-11-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:

import numpy as np
import datetime

# Define the start and end dates for July 2016
start_date = datetime.date(2016, 7, 1)
end_date = datetime.date(2016, 7, 31)

# Generate an array of dates for the month of July 2016
dates = np.arange(start_date, end_date + datetime.timedelta(days=1), dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:

import numpy as np

# Example arrays A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Compute ((A+B) * (-A/2)) in place
np.multiply(A + B, -A / 2, out=A)

print(A)

UFuncTypeError: ignored

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:

import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10  # Adjust the size as needed

# Method 1: Using numpy.floor
method1_result = np.floor(random_array)

# Method 2: Using numpy.trunc
method2_result = np.trunc(random_array)

# Method 3: Using numpy.astype(int)
method3_result = random_array.astype(int)

# Method 4: Using numpy.ceil and numpy.floor
method4_result = (random_array + 0.5).astype(int)

# Print the results
print("Original array:", random_array)
print("Method 1:", method1_result)
print("Method 2:", method2_result)
print("Method 3:", method3_result)
print("Method 4:", method4_result)

Original array: [9.1082406  3.67433702 4.51118828 8.82892966 1.25738242]
Method 1: [9. 3. 4. 8. 1.]
Method 2: [9. 3. 4. 8. 1.]
Method 3: [9 3 4 8 1]
Method 4: [9 4 5 9 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:

import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.zeros((5, 5)) + np.arange(5)

print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
import numpy as np

# Define a generator function that generates 10 integers
def integer_generator():
    for i in range(10):
        yield i

# Use np.fromiter to build an array from the generator
array_from_generator = np.fromiter(integer_generator(), dtype=int)

print(array_from_generator)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:

import numpy as np

# Create a vector with values ranging from 0 to 1 (exclusive)
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:

import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)

print("Original vector:", random_vector)
print("Sorted vector:", sorted_vector)

Original vector: [0.64227521 0.97203163 0.71922829 0.74754217 0.02046221 0.9041288
 0.61096618 0.80162643 0.05554408 0.54072154]
Sorted vector: [0.02046221 0.05554408 0.54072154 0.61096618 0.64227521 0.71922829
 0.74754217 0.80162643 0.9041288  0.97203163]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:

import numpy as np

# Create a small array
small_array = np.array([1, 2, 3, 4, 5])

# Sum using np.sum
sum_np = np.sum(small_array)

# Sum using built-in Python sum function
sum_python = sum(small_array)

print("Sum using np.sum:", sum_np)
print("Sum using Python sum:", sum_python)

Sum using np.sum: 15
Sum using Python sum: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:

import numpy as np

# Create two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Array A: [0.75759997 0.85358198 0.44273668 0.40123285 0.51830076]
Array B: [0.13339861 0.885616   0.69134331 0.64422054 0.12409434]
Arrays A and B are not equal.


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:

import numpy as np

# Create a mutable array
mutable_array = np.array([1, 2, 3, 4, 5])

# Make the array read-only
read_only_array = np.array([1, 2, 3, 4, 5])
read_only_array.flags.writeable = False

# Attempt to modify the mutable and read-only arrays
mutable_array[0] = 10  # This is allowed
# read_only_array[0] = 10  # Uncommenting this line would result in a ValueError

print("Mutable array:", mutable_array)
print("Read-only array:", read_only_array)

Mutable array: [10  2  3  4  5]
Read-only array: [1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:

import numpy as np

# Create a random 10x2 matrix representing cartesian coordinates
cartesian_coordinates = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# Convert to polar coordinates
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

# Create a 10x2 matrix representing polar coordinates
polar_coordinates = np.column_stack((r, theta))

print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nPolar Coordinates:")
print(polar_coordinates)

Cartesian Coordinates:
[[0.01824156 0.98363914]
 [0.44672763 0.94436846]
 [0.60143393 0.31383661]
 [0.01341692 0.22646927]
 [0.74234427 0.62640579]
 [0.25768837 0.64267264]
 [0.1049113  0.19312034]
 [0.66012345 0.22806928]
 [0.1529188  0.10061179]
 [0.33682878 0.64196369]]

Polar Coordinates:
[[0.98380827 1.55225348]
 [1.04469965 1.12894529]
 [0.67839236 0.48094608]
 [0.22686636 1.51162161]
 [0.9713183  0.70089597]
 [0.69240986 1.18945948]
 [0.21977681 1.07315552]
 [0.69841146 0.33265574]
 [0.18304888 0.58193851]
 [0.72496276 1.08759622]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:

import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

print("Original vector:", random_vector)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value by 0
random_vector[max_index] = 0

print("Vector after replacing the maximum value:", random_vector)

Original vector: [0.43511175 0.20307681 0.54480198 0.64600965 0.76744609 0.94363375
 0.26046406 0.57458538 0.60289109 0.66114253]
Vector after replacing the maximum value: [0.43511175 0.20307681 0.54480198 0.64600965 0.76744609 0.
 0.26046406 0.57458538 0.60289109 0.66114253]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:

import numpy as np

# Define the size of the array
size = 5

# Create a structured array with x and y coordinates
structured_array = np.zeros(size, dtype=[('x', float), ('y', float)])

# Fill the array with coordinates covering the [0,1]x[0,1] area
structured_array['x'] = np.linspace(0, 1, size)
structured_array['y'] = np.linspace(0, 1, size)

print(structured_array)

[(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:

import numpy as np

# Given arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1 / (X[:, np.newaxis] - Y)

print("Cauchy Matrix C:")
print(C)

Cauchy Matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
import numpy as np

# Integer types
int_types = [np.int8, np.int16, np.int32, np.int64]
for int_type in int_types:
    info = np.iinfo(int_type)
    print(f"{int_type.__name__}: Min = {info.min}, Max = {info.max}")

# Floating-point types
float_types = [np.float16, np.float32, np.float64]
for float_type in float_types:
    info = np.finfo(float

SyntaxError: ignored

#### 49. How to print all the values of an array? (★★☆)

In [ ]:

import numpy as np

# Create an example array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print all values of the array
print("All values of the array:")
print(my_array)

All values of the array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
import numpy as np

# Create a vector
vector = np.array([1.2, 2.5, 3.7, 4.1, 5.3])

# Given scalar
scalar = 3.0

# Find the closest value in the vector
closest_value = vector[np.argmin(np.abs(vector - scalar))]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest value:", closest_value)

Vector: [1.2 2.5 3.7 4.1 5.3]
Scalar: 3.0
Closest value: 2.5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:

import numpy as np

# Create a structured array with fields: x, y, r, g, b
structured_array = np.zeros(5, dtype=[('x', float), ('y', float), ('r', int), ('g', int), ('b', int)])

# Fill the array with example data
structured_array['x'] = np.random.rand(5)
structured_array['y'] = np.random.rand(5)
structured_array['r'] = np.random.randint(0, 256, 5)  # Random values between 0 and 255
structured_array['g'] = np.random.randint(0, 256, 5)
structured_array['b'] = np.random.randint(0, 256, 5)

print("Structured Array:")
print(structured_array)

Structured Array:
[(0.47336119, 0.92739548, 225, 233, 208)
 (0.42013652, 0.06829043, 146, 208, 170)
 (0.6148022 , 0.81781207, 174, 139, 106)
 (0.44113931, 0.34915147, 201,  39,  86)
 (0.31770823, 0.21384387, 179,   0, 214)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.33188071 0.57516787 0.64063269 0.32595508 0.09113634
  0.26923987 0.13719371 0.20107459 0.32208652]
 [0.33188071 0.         0.34113688 0.94649961 0.48141741 0.41068164
  0.45205675 0.26891965 0.52846567 0.40046459]
 [0.57516787 0.34113688 0.         1.21516071 0.51265846 0.61832101
  0.52294669 0.57551674 0.77015052 0.40849357]
 [0.64063269 0.94649961 1.21516071 0.         0.82843943 0.60315412
  0.77901841 0.6790016  0.44665399 0.8905908 ]
 [0.32595508 0.48141741 0.51265846 0.82843943 0.         0.27927455
  0.0586725  0.44594888 0.41511965 0.10462654]
 [0.09113634 0.41068164 0.61832101 0.60315412 0.27927455 0.
  0.22062581 0.22574344 0.15753433 0.30420282]
 [0.26923987 0.45205675 0.52294669 0.77901841 0.0586725  0.22062581
  0.         0.39282366 0.35873837 0.1217989 ]
 [0.13719371 0.26891965 0.57551674 0.6790016  0.44594888 0.22574344
  0.39282366 0.         0.2844457  0.41927625]
 [0.20107459 0.52846567 0.77015052 0.44665399 0.41511965 0.15753433
  0.35873837 0.28444

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:

import numpy as np

# Create a float (32 bits) array
float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)

# Convert to an integer (32 bits) array in place
int_array = float_array.view(np.int32)

print("Original float array:", float_array)
print("Converted integer array:", int_array)

Original float array: [1.5 2.7 3.9]
Converted integer array: [1069547520 1076677837 1081711002]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:

import numpy as np

# Read the file using genfromtxt
data = np.genfromtxt('example.txt', delimiter=',', filling_values=np.nan)

print("Data from file:")
print(data)

FileNotFoundError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:

import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Enumerate over the elements of the array
for index, value in np.ndenumerate(array):
    print("Index:", index, "Value:", value)

Index: (0, 0) Value: 1
Index: (0, 1) Value: 2
Index: (0, 2) Value: 3
Index: (1, 0) Value: 4
Index: (1, 1) Value: 5
Index: (1, 2) Value: 6
Index: (2, 0) Value: 7
Index: (2, 1) Value: 8
Index: (2, 2) Value: 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:

import numpy as np
import matplotlib.pyplot as plt

def gaussian_2d(x, y, mu, sigma):
    return np.exp(-(x - mu[0])**2 / (2 * sigma[0]**2) - (y - mu[1])**2 / (2 * sigma[1]**2))

# Size of the array
rows, cols = 5, 5

# Mean and standard deviation for each dimension
mu = [2, 2]
sigma = [1, 1]

# Create a 2D array with Gaussian-like values
x, y = np.meshgrid(np.arange(cols), np.arange(rows))
gaussian_array = gaussian_2d(x, y, mu, sigma)

print("2D Gaussian-like Array:")
print(gaussian_array)

# Plotting the array
plt.imshow(gaussian_array, cmap='viridis', interpolation='nearest', origin='upper')
plt.title('2D Gaussian-like

SyntaxError: ignored

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:

import numpy as np

# Size of the 2D array
rows, cols = 4, 5

# Number of elements to randomly place
p = 8

# Create a 2D array filled with zeros
array = np.zeros((rows, cols), dtype=int)

# Generate random indices
random_indices = np.random.choice(rows * cols, p, replace=False)

# Assign random values to those indices
array.flat[random_indices] = 1

print("Randomly Placed 2D Array:")
print(array)

Randomly Placed 2D Array:
[[0 1 0 0 0]
 [0 1 0 1 0]
 [0 1 0 0 0]
 [1 0 1 1 1]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:

import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Subtract the mean of each row
matrix_mean_subtracted = matrix - np.mean(matrix, axis=1, keepdims=True)

print("Original Matrix:")
print(matrix)
print("Matrix with mean subtracted from each row:")
print(matrix_mean_subtracted)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix with mean subtracted from each row:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
import numpy as np

# Create a 2D array
array_to_sort = np.array([[3, 2, 1],
                          [6, 5, 4],
                          [9, 8, 7]])

# Specify the column index to sort by (nth column)
n = 1

# Sort the array by the nth column
sorted_array = array_to_sort[array_to_sort[:, n].argsort()]

print("Original Array:")
print(array_to_sort)
print("Sorted Array by the nth column:")
print(sorted_array)

Original Array:
[[3 2 1]
 [6 5 4]
 [9 8 7]]
Sorted Array by the nth column:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:

import numpy as np

# Create a 2D array with some null columns
array_with_null_columns = np.array([[1, 0, 3],
                                     [0, 0, 0],
                                     [4, 0, 6]])

# Check for null columns
null_columns = np.all(array_with_null_columns == 0, axis=0)

print("Original Array:")
print(array_with_null_columns)
print("Null Columns:")
print(null_columns)

Original Array:
[[1 0 3]
 [0 0 0]
 [4 0 6]]
Null Columns:
[False  True False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
def find_nearest_value(array, target):
    return min(array, key=lambda x: abs(x - target))

# Example usage:
my_array = [1, 3, 5, 7, 9]
given_value = 6
nearest_value = find_nearest_value(my_array, given_value)

print(f"The nearest value to {given_value} in the array is {nearest_value}.")

The nearest value to 6 in the array is 5.


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:

import numpy as np

# Create two arrays with shapes (1,3) and (3,1)
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Initialize an iterator for each array
iter1 = np.nditer(array1)
iter2 = np.nditer(array2)

# Initialize a variable to store the sum
result_sum = 0

# Iterate over the elements and compute the sum

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:

class NamedArray:
    def __init__(self, name, array):
        self.name = name
        self.array = array

# Example usage:
my_named_array = NamedArray("ExampleArray", [1, 2, 3, 4, 5])

# Accessing the name and array attributes
print("Array Name:", my_named_array.name)
print("Array Values:", my_named_array.array)

Array Name: ExampleArray
Array Values: [1, 2, 3, 4, 5]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:

import numpy as np

def add_one_to_indices(vector, indices):
    unique_indices, counts = np.unique(indices, return_counts=True)

    # Add 1 to each element at the unique indices
    vector[unique_indices] += 1

    # Adjust for repeated indices
    vector[unique_indices] += counts - 1

    return vector

# Example usage:
original_vector = np.array([0, 1, 2, 3, 4])
index

NameError: ignored

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
import numpy as np

def accumulate_elements(X, I, F):
    np.add.at(F, I, X)
    return F

# Example usage:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 1, 3])
F = np.zeros(4, dtype

SyntaxError: ignored

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:

import numpy as np

def count_unique_colors(image):
    unique_colors = np.unique(image.reshape(-1, 3), axis=0)
    num_unique_colors = len(unique_colors)
    return num_unique_colors

# Example usage:
w, h = 5, 5  # Replace with the actual dimensions of your image
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

num_colors = count_unique_colors(image)

print("Number of Unique Colors:", num_colors)

Number of Unique Colors: 25


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
import numpy as np

# Create a random four-dimensional array (replace with your actual array)
four_dim_array = np.random.rand(2, 3, 4, 5)

# Sum over the last two axes (axis=(2, 3))
sum_over_last_two_axes = np.sum(four_dim_array, axis=(2, 3))

print("Original Array Shape:", four_dim_array.shape)
print("Sum Over Last Two Axes Shape:", sum_over_last_two_axes.shape)

Original Array Shape: (2, 3, 4, 5)
Sum Over Last Two Axes Shape: (2, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:

import numpy as np

def compute_means_by_subset(D, S):
    unique_indices = np.unique(S)
    subset_means = [np.mean(D[S == idx]) for idx in unique_indices]
    return subset_means

# Example usage:
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
S = np.array([0, 1, 0, 1, 2, 2, 1, 0, 2])

means_by_subset = compute_means

NameError: ignored

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:

import numpy as np

# Create two matrices A and B (replace with your actual matrices)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# Calculate the dot product
dot_product = np.dot(A, B)

# Get the diagonal of the dot product
diagonal_dot_product = np.diagonal(dot_product)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nDot Product:")
print(dot_product)
print("\nDiagonal of Dot Product:")
print(diagonal_dot_product)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Dot Product:
[[ 58  64]
 [139 154]]

Diagonal of Dot Product:
[ 58 154]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
import numpy as np

# Original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Build a new vector with 3 consecutive zeros interleaved
new_vector = np.zeros(len(original_vector) + 3 * (len(original_vector) - 1))
new_vector[::4] = original_vector

print("Original Vector:", original_vector)
print("New Vector with 3 Consecutive Zeros Interleaved:", new_vector)

Original Vector: [1 2 3 4 5]
New Vector with 3 Consecutive Zeros Interleaved: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:

import numpy as np

# Create a 3D array of dimensions (5, 5, 3) (replace with your actual data)
array_3d = np.random.rand(5, 5, 3)

# Create a 2D array of dimensions (5, 5) (replace with your actual data)
array_2d = np.random.rand(5, 5)

# Multiply the arrays along the last axis
result = array_3d * array_2d[:, :, np.newaxis]

print("3D Array (5, 5, 3):")
print(array_3d)
print("\n2D Array (5, 5):")
print(array_2d)
print("\nResult after Multiplication:")
print(result)

3D Array (5, 5, 3):
[[[0.67596855 0.47650321 0.77231326]
  [0.68669408 0.21088467 0.55194237]
  [0.38451653 0.7829248  0.06955627]
  [0.54413514 0.99647725 0.08307634]
  [0.64896516 0.38693486 0.71911364]]

 [[0.98320542 0.07740978 0.32032655]
  [0.23914554 0.80885815 0.52799061]
  [0.93269436 0.5345954  0.7455812 ]
  [0.26860925 0.65122947 0.3434735 ]
  [0.19339181 0.91253627 0.49905258]]

 [[0.70700996 0.51098322 0.96297012]
  [0.58270466 0.42232494 0.07555793]
  [0.26361357 0.51692828 0.96275959]
  [0.42553632 0.84038361 0.9976322 ]
  [0.41017057 0.69094598 0.09981369]]

 [[0.68706039 0.61701676 0.80216562]
  [0.27397975 0.12703513 0.38413305]
  [0.41427507 0.8432717  0.150752  ]
  [0.33296913 0.57360087 0.1003232 ]
  [0.56844117 0.8751543  0.77513725]]

 [[0.73192021 0.13402173 0.13217829]
  [0.94643852 0.5007798  0.43050853]
  [0.45418288 0.94865963 0.84482609]
  [0.6574412  0.78639058 0.75428163]
  [0.00868795 0.94495835 0.03224216]]]

2D Array (5, 5):
[[0.79891128 0.30056698 0.4

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
import numpy as np

# Create a sample 2D array (replace with your actual data)
my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Swap rows 1 and 2 (0-based indexing)
row1, row2 = 1, 2
my_array[row1], my_array[row2] = my_array[row2].copy(), my_array[row1].copy()

print("Original Array:")
print(my_array)

Original Array:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:

import numpy as np

# Given sorted array C (replace with your actual data)
C = np.array([0, 1, 2, 2, 3, 3, 3, 4, 4])

# Produce array A
A = np.repeat(np.arange(len(C)), C)

print("Given sorted array C:",

SyntaxError: ignored

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:

import numpy as np

def sliding_average(arr, window_size):
    shape = (arr.size - window_size + 1, window_size)
    strides = (arr.itemsize, arr.itemsize)
    windowed_arr = np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)
    return windowed_arr.mean(axis=1)

# Example usage:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3

averages = sliding_average(array, window_size)

print("Original Array:", array)
print("Averages with a Sliding Window of Size", window_size, ":", averages)

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Averages with a Sliding Window of Size 3 : [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:

import numpy as np

# Create a one-dimensional array Z (replace with your actual data)
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Build the two-dimensional array with shifted rows
num_rows = 3
result_array = np.lib.stride_tricks.sliding_window_view(Z, (num_rows,)).T

print("Original Array Z:", Z)
print("Resulting Two-Dimensional Array:")
print(result_array)

Original Array Z: [1 2 3 4 5 6 7 8 9]
Resulting Two-Dimensional Array:
[[1 2 3 4 5 6 7]
 [2 3 4 5 6 7 8]
 [3 4 5 6 7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:

# Initial boolean value
my_boolean = True

# Negate inplace
my_boolean = not my_boolean

print("Negated Boolean:", my_boolean)

Negated Boolean: False


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
import numpy as np

def distance_point_to_line_segment(p, P0, P1):
    # Convert points to numpy arrays for vectorized operations
    p, P0, P1 = np.array(p), np.array(P0), np.array(P1)

    # Vector representing the line segment
    v = P1 - P0

    # Vector from P0 to the point p
    w = p - P0

    # Projection of w onto the line segment
    c1 = np.dot(w, v)
    c2 = np.dot(v, v)

    # Calculate the parameter t for the projection point
    t = c1 / c2

    # Clamp t to ensure the projection point lies within the line segment
    t = np.clip(t, 0, 1)

    # Projection point on the line segment
    projection_point = P0 + t * v

    # Calculate the distance from the point p to the projection point
    distance = np.linalg.norm(p - projection_point

SyntaxError: ignored

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:

import numpy as np

def distance_points_to_lines(P, P0, P1):
    # Convert points to numpy arrays for vectorized operations
    P, P0, P1 = np.array(P), np.array(P0), np.array(P1)

    # Vector representing the line segments
    v = P1 - P0

    # Vector from P0 to the points P
    w = P[:, np.newaxis] - P0

    # Projection of w onto the line segments
    c1 = np.einsum('ij,ij->i', w, v)
    c2 = np.einsum('ij,ij->i', v, v)

    # Calculate the parameter t for the projection points
    t = c1 / c2

    # Clamp t to ensure the projection points lie within the line segments
    t = np.clip(t, 0, 1)

    # Projection points on the line segments
    projection_points = P0 + t[:, np.newaxis] * v

    # Calculate the distances from the points P to the projection points
    distances = np.linalg.norm(P - projection_points, axis=1)

    return distances

# Example usage:
P0 = [[0, 0

SyntaxError: ignored

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:

import numpy as np

def extract_subpart(array, center, shape, fill_value=0):
    """
    Extracts a subpart from the array centered on the given element with the specified shape.

    Parameters:
    - array: The input array.
    - center: The coordinates of the center element.
    - shape: The shape of the subpart.
    - fill_value: The value to fill when padding is necessary.

    Returns:
    - subpart: The extracted subpart.
    """
    array = np.array(array)
    center = np.array(center)
    shape = np.array(shape)

    start_index = np.maximum(center - shape // 2, 0)
    end_index = start_index + shape

    slices = [slice(start, end) for start, end in zip(start_index, end_index)]

    subpart = np.full(shape, fill_value, dtype=array.dtype)
    subpart_slices = [slice(0, size) for size in subpart.shape]

    subpart[slices] = array[tuple(subpart_slices)]

    return subpart

# Example usage:
my_array = np.random.randint(0, 10, (5, 5))
center_element = (2, 2)
subpart_shape = (3, 3)

result = extract_subpart(my_array, center_element, subpart_shape, fill_value=-1)

print("Original Array:")
print(my_array)
print("\nExtracted Subpart:")
print(result)

IndexError: ignored

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:

import numpy as np

# Given array Z
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

# Define the window size
window_size = 4

# Calculate the shape and strides to create the array R
shape = (len(Z) - window_size + 1, window_size)
strides = (Z.itemsize, Z.itemsize)

# Create the array R
R = np.lib.stride_tricks.as_strided(Z, shape=shape, strides=strides)

print("Array Z:", Z)
print("Generated Array R:")
print(R)

Array Z: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Generated Array R:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:

import numpy as np

# Create a matrix (replace with your actual data)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Matrix:")
print(matrix)
print("\nRank of the Matrix:", rank)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of the Matrix: 2


#### 83. How to find the most frequent value in an array?

In [ ]:

import numpy as np

# Create an array (replace with your actual data)
my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5])

# Find the most frequent value
most_frequent_value = np.bincount(my_array).argmax()

print("Array:",

SyntaxError: ignored

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:

import numpy as np

# Create a random 10x10 matrix (replace with your actual data)
matrix = np.random.random((10, 10))

# Define the block size
block_size = 3

# Extract all contiguous 3x3 blocks
blocks = np.lib.stride_tricks.sliding_window_view(matrix, (block_size, block_size))

# Print the extracted blocks
print("Original Matrix:")
print(matrix)
print

Original Matrix:
[[0.36629583 0.92398202 0.83763806 0.05426439 0.94495566 0.69107849
  0.12908202 0.40441013 0.5354404  0.81785015]
 [0.95514817 0.52583137 0.96209889 0.09192706 0.14302921 0.09356744
  0.15776354 0.17541696 0.28030021 0.81865454]
 [0.6874737  0.48952441 0.37521078 0.51330894 0.46083247 0.82215514
  0.08455219 0.93459927 0.75092286 0.37924647]
 [0.1359164  0.07132426 0.39890347 0.69681705 0.88815342 0.87549747
  0.1852637  0.5697171  0.83863103 0.24222983]
 [0.50415002 0.39072455 0.58496595 0.56627097 0.20091741 0.0924324
  0.17107443 0.06421504 0.08784526 0.49986209]
 [0.18509138 0.04402217 0.3098255  0.58133231 0.5405279  0.89122079
  0.01903468 0.67127429 0.29210766 0.34723114]
 [0.15947499 0.59770614 0.51005568 0.19198266 0.63737178 0.41361915
  0.09644496 0.79018618 0.15436494 0.11185427]
 [0.59648536 0.23369597 0.96115362 0.87492864 0.61800212 0.42889129
  0.07057825 0.43924078 0.70576197 0.53211798]
 [0.28278588 0.30477732 0.01542377 0.32458753 0.04304821 0.39557

<function print>

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:

import numpy as np

class SymmetricArray(np.ndarray):
    def __getitem__(self, index):
        # Swap indices to enforce symmetry
        if isinstance(index, tuple) and len(index) == 2:
            i, j = index
            return super().__getitem__((max(i, j), min(i, j)))
        return super().__getitem__(index)

# Create a symmetric array
Z = SymmetricArray(shape=(3, 3))

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:

import numpy as np

# Number of matrices (replace with your actual value)
p = 3

# Matrix dimensions (replace with your actual value)
n = 4

# Create p matrices and vectors (replace with your actual data)
matrices = [np.random.rand(n, n) for _ in range(p)]
vectors = [np.random.rand(n, 1) for _ in range(p)]

# Compute the sum of the p matrix products
result = np.sum([np.dot(matrices[i], vectors[i]) for i in range(p)], axis=0)

print("Matrices:")
print(matrices)
print("\nVectors:")
print

Matrices:
[array([[0.47223906, 0.09098305, 0.18974724, 0.26016241],
       [0.55339354, 0.6134681 , 0.16032581, 0.07915272],
       [0.31377603, 0.96206698, 0.88426999, 0.77375955],
       [0.83499775, 0.30055439, 0.84065776, 0.83515629]]), array([[0.73336534, 0.12281969, 0.55582087, 0.1729123 ],
       [0.09501603, 0.44915456, 0.78870186, 0.59297801],
       [0.35917942, 0.11209969, 0.96055986, 0.2149592 ],
       [0.96255225, 0.58902513, 0.29741433, 0.41272   ]]), array([[0.78000427, 0.54025636, 0.33353294, 0.56776217],
       [0.53502214, 0.38258604, 0.39294401, 0.7444935 ],
       [0.44062446, 0.38931868, 0.95589451, 0.67109399],
       [0.47372499, 0.20732738, 0.07100672, 0.38126691]])]

Vectors:


<function print>

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:

import numpy as np

# Create a 16x16 array (replace with your actual data)
array_16x16 = np.random.rand(16, 16)

# Define block size
block_size = 4

# Reshape the array to facilitate block-sum calculation

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def update(frameNum, img, grid, N):
    newGrid = grid.copy()
    for i in range(N):
        for j in range(N):
            total = int((grid[i, (j-1)%N] + grid[i, (j+1)%N] +
                         grid[(i-1)%N, j] + grid[(i+1)%N, j] +
                         grid[(i-1)%N, (j-1)%N] + grid[(i-1)%N, (j+1)%N] +
                         grid[(i+1)%N

SyntaxError: ignored

#### 89. How to get the n largest values of an array (★★★)

In [ ]:

import numpy as np

# Create an array (replace with your actual data)
my_array = np.array([3, 1, 4, 1,

SyntaxError: ignored

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:

from itertools import product

# Replace these with your actual vectors
vector1 = [1, 2]
vector2 = ['a', 'b', 'c']
vector3 = [True, False]

# Build the Cartesian product
cartesian_product = list

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
import numpy as np

# Create a regular array
regular_array = np.array([(1, 'Alice', 25),
                          (2, 'Bob', 30),
                          (3, 'Charlie', 22)],
                         dtype=[('id', int), ('name', 'U10'), ('age', int)])

# Convert the regular array to a record array
record_array = np.core.records.fromarrays(regular_array.T,
                                          dtype={'names': ['

SyntaxError: ignored

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:

import numpy as np

# Create a large vector Z (replace with your actual data)
Z = np.random.rand(1000000)

# Method 1: Using NumPy's np.power
result_method1 = np.power(Z, 3)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
import numpy as np

# Create arrays A and B (replace with your actual data)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [3, 1, 2],
              [6, 4, 5],

SyntaxError: ignored

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
import numpy as np

# Create a 10x3 matrix (replace with your actual data)
matrix = np.random.randint(1, 4, (10, 3))

# Define a target row with unequal values
target_row = np.array([2, 2, 3])

# Find rows with unequal values compared to the target row
unequal_rows = np.any(matrix != target_row, axis=1)

result = matrix[unequal_rows]

print("Original Matrix:")
print(matrix)
print("\nTarget

SyntaxError: ignored

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:

import numpy as np

# Create a vector of ints (replace with your actual data)
int_vector = np.array([5, 10, 15, 3, 7])

# Convert to binary representation
binary_matrix = np.array(list(map(list, np.binary_repr(int_vector).astype(int))))

print("Original Vector of Ints:")
print(int_vector)
print("\

SyntaxError: ignored

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:

import numpy as np

# Create a two-dimensional array (replace with your actual data)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [1, 2, 3],
                     [7, 8, 9],
                     [4, 5, 6]])

# Extract unique rows
unique_rows = np.unique(array_2d, axis=0)

print("Original 2D Array:")
print(array_2d)
print("\nUnique Rows:")
print(unique_rows)
``

SyntaxError: ignored

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Einsum equivalent for inner product
inner_product = np.einsum('i,i->', A, B)

print("Inner Product:", inner_product)

Inner Product: 32


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:

import numpy as np

# Replace X and Y with your actual data
X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 3, 5, 4, 1])

# Number of equidistant samples
num_samples = 10

# Calculate the total path length
path_length = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
total_length = path_length[-1]

# Calculate the equidistant sample points
equidistant_samples = np.linspace(0, total_length, num_samples)

# Interpolate X and Y to find corresponding points on the path
sampled_X = np.interp(equidistant_samples, path_length, X)
sampled_Y = np.interp(equidistant_samples, path_length, Y)

print("Original X and Y:")

ValueError: ignored

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:

import numpy as np

# Replace X with your actual 2D array
X = np.array([[1, 2, 3],
              [2, 4, 2],
              [3, 2, 1],
              [1.5, 2.5, 3],
              [1, 1, 8]])

# Replace n with your desired value
n =

SyntaxError: ignored

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
import numpy as np

# Replace X with your actual 1D array
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Number of bootstrap samples
N = 1000

# Create an array to store bootstrap sample means
bootstrap_means = np.empty(N)

# Perform bootstrap resampling
for i in

SyntaxError: ignored